[package]
name = "leetcode-runner-cli"
version = "0.2.2"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
colored = "2.0.0"
reqwest ={version =  "0.11.16", features=["blocking", "json"]}
serde = {version="1.0.159", features=["derive"]}
serde_json = "1.0.95"
