[package]
name = "leetcode-runner-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
colored = "2.0.0"
reqwest ={version =  "0.11.15", features=["blocking", "json"]}
serde = {version="1.0.158", features=["derive"]}
serde_json = "1.0.94"
